debug: true
initSources: true
entries:
  - name: terraform
    upstream:
      type: regex
      url: https://releases.hashicorp.com/terraform/
      regex: '.*>terraform_(.*)<.*'
    downstream:
      type: command
      command: |
        terraform version | sed -rn 's/.*v([0-9\.]+)/\1/p'
    hooks:
      - type: download
        url: 'https://releases.hashicorp.com/terraform/{{.Version}}/terraform_{{.Version}}_linux_amd64.zip'
        dest: '$HOME/.local/bin/terraform'
        extract:
          file: terraform

  - name: helmfile
    upstream:
      type: github
      repo: roboll/helmfile
    downstream:
      type: command
      command: |
        helmfile -v | sed -rn 's/.*v([0-9\.]+)/\1/p'
    hooks:
      - type: download
        github:
          repo: roboll/helmfile
          asset: helmfile_linux_amd64
        dest: '$HOME/.local/bin/helmfile'
        chmod: 755

  - name: argocd
    upstream:
      type: github
      repo: argoproj/argo-cd
    downstream:
      type: command
      command: |
        argocd version --short --client | sed -rn 's/.*v([0-9\.]+).*/\1/p'
    hooks:
      - type: download
        github:
          repo: argoproj/argo-cd
          asset: argocd-linux-amd64
        dest: '$HOME/.local/bin/argocd'
        chmod: 755
