mode: dev
entries:
  - name: terraform
    source:
      type: command
      command: |
        terraform version | sed -E 's/.*v(.*)/\1/'
    provider:
      type: regex
      url: 'https://releases.hashicorp.com/terraform/'
      regex: '.*>terraform_(.*)<.*'
    hooks:
      - type: download
        url: 'https://releases.hashicorp.com/terraform/{{.Version}}/terraform_{{.Version}}_linux_amd64.zip'
        dest: '$HOME/.local/bin/terraform'
        extract:
          file: terraform
  # - https://github.com/mholt/archiver/releases
  # - helmfile
