debug: true
initSources: true
entries:
  - name: terraform
    source:
      type: command
      command: |
        terraform version | sed -rn 's/.*v([0-9\.]+)/\1/p'
    provider:
      type: regex
      url: https://releases.hashicorp.com/terraform/
      regex: '.*>terraform_(.*)<.*'
    hooks:
      - type: download
        url: 'https://releases.hashicorp.com/terraform/{{.Version}}/terraform_{{.Version}}_linux_amd64.zip'
        dest: '$HOME/.local/bin/terraform'
        extract:
          file: terraform

  - name: helmfile
    source:
      type: command
      command: |
        helmfile -v | sed -rn 's/.*v([0-9\.]+)/\1/p'
    provider:
      type: github
      repo: roboll/helmfile
    hooks:
      - type: download
        github:
          repo: roboll/helmfile
          asset: helmfile_linux_amd64
        dest: '$HOME/.local/bin/helmfile'
        chmod: 755

  - name: archiver
    source:
      type: command
      command: |
        echo 3.1.0
    provider:
      type: github
      repo: mholt/archiver
    hooks:
      - type: download
        github:
          repo: mholt/archiver
          asset: arc_linux_amd64
        dest: '$HOME/.local/bin/archiver'
        chmod: 755
